# syntax=docker/dockerfile:1
# Multistage Dockerfile to serve in production
# Stage 0: build site
FROM node:16-alpine as build-stage

ENV APP_HOME=/app
WORKDIR ${APP_HOME}

COPY package*.json .
RUN set -eux \
    && yarn install

COPY . .

CMD ["yarn", "build"]

# Stage 1: serve
FROM nginx:1.23.0-alpine

COPY --from=build-stage /app/build /usr/share/nginx/html

COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf