---
# this should mainly be used for testing
version: "3.9"

services:
    # backend
    api:
        container_name: api
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        init: true

    # frontend
    frontend:
        container_name: frontend
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        init: true
