---
name: Linters

on: push

jobs:
    "Prettier-API":
        runs-on: ubuntu-latest
        container: node:16

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              working-directory: api
              run: yarn install

            - name: Run Prettier Check
              working-directory: api
              run: yarn run prettier:check

    "Prettier-Frontend":
        runs-on: ubuntu-latest
        container: node:16

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              working-directory: frontend
              run: yarn install

            - name: Run Prettier Check
              working-directory: frontend
              run: yarn run prettier:check

    "Tests":
        runs-on: ubuntu-latest
        container: node:16

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              working-directory: api
              run: yarn install

            - name: Run Prettier Check
              working-directory: api
              run: yarn test
